services:
  db:
    image: postgres
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
  card_scanner:
    build: ./card_scanner
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=${JWT_SECRET}  # Will use the same JWT secret as the main application
    depends_on:
      - db
